"""create core tables

Revision ID: c202f959c643
Revises: 
Create Date: 2026-08-27 14:59:36.357771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c202f959c643'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='PUBLISHED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_books'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('words',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('phonetic', sa.String(length=100), nullable=True),
    sa.Column('meaning_zh', sa.Text(), nullable=True),
    sa.Column('simple_definition', sa.Text(), nullable=True),
    sa.Column('example_sentence', sa.Text(), nullable=True),
    sa.Column('example_translation', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.Text(), nullable=True),
    sa.Column('part_of_speech', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_words')),
    sa.UniqueConstraint('word', name=op.f('uq_words_word'))
    )
    op.create_table('book_pages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_pages_book_id_books'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_book_pages'))
    )
    op.create_index(op.f('ix_book_pages_book_id'), 'book_pages', ['book_id'], unique=False)
    op.create_table('book_words',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('word_id', sa.Uuid(), nullable=False),
    sa.Column('is_key_word', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_words_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], name=op.f('fk_book_words_word_id_words'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'word_id', name=op.f('pk_book_words'))
    )
    op.create_table('children',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('reading_level', sa.String(length=20), nullable=True),
    sa.Column('vocabulary_size', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], name=op.f('fk_children_parent_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_children'))
    )
    op.create_index(op.f('ix_children_parent_id'), 'children', ['parent_id'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=30), nullable=True),
    sa.Column('correct_option', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_quiz_questions_book_id_books'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_questions'))
    )
    op.create_index(op.f('ix_quiz_questions_book_id'), 'quiz_questions', ['book_id'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('selected_option', sa.String(length=10), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('fk_quiz_attempts_child_id_children'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], name=op.f('fk_quiz_attempts_question_id_quiz_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_attempts'))
    )
    op.create_index(op.f('ix_quiz_attempts_child_id'), 'quiz_attempts', ['child_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_question_id'), 'quiz_attempts', ['question_id'], unique=False)
    op.create_table('quiz_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('option_key', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], name=op.f('fk_quiz_options_question_id_quiz_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_options'))
    )
    op.create_index(op.f('ix_quiz_options_question_id'), 'quiz_options', ['question_id'], unique=False)
    op.create_table('reading_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), server_default='0', nullable=False),
    sa.Column('progress', sa.Float(), server_default='0', nullable=False),
    sa.Column('completed', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_reading_sessions_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('fk_reading_sessions_child_id_children'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reading_sessions'))
    )
    op.create_index(op.f('ix_reading_sessions_book_id'), 'reading_sessions', ['book_id'], unique=False)
    op.create_index(op.f('ix_reading_sessions_child_id'), 'reading_sessions', ['child_id'], unique=False)
    op.create_table('user_words',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('word_id', sa.Uuid(), nullable=False),
    sa.Column('encounter_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('click_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('audio_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('correct_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('wrong_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('mastery_score', sa.Float(), server_default='0', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('fk_user_words_child_id_children'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], name=op.f('fk_user_words_word_id_words'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_words')),
    sa.UniqueConstraint('child_id', 'word_id', name=op.f('uq_user_words_child_id'))
    )
    op.create_index(op.f('ix_user_words_child_id'), 'user_words', ['child_id'], unique=False)
    op.create_index(op.f('ix_user_words_word_id'), 'user_words', ['word_id'], unique=False)
    op.create_table('reading_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('word_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_reading_events_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('fk_reading_events_child_id_children'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['reading_sessions.id'], name=op.f('fk_reading_events_session_id_reading_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], name=op.f('fk_reading_events_word_id_words'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reading_events'))
    )
    op.create_index(op.f('ix_reading_events_book_id'), 'reading_events', ['book_id'], unique=False)
    op.create_index(op.f('ix_reading_events_child_id'), 'reading_events', ['child_id'], unique=False)
    op.create_index(op.f('ix_reading_events_session_id'), 'reading_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_reading_events_word_id'), 'reading_events', ['word_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reading_events_word_id'), table_name='reading_events')
    op.drop_index(op.f('ix_reading_events_session_id'), table_name='reading_events')
    op.drop_index(op.f('ix_reading_events_child_id'), table_name='reading_events')
    op.drop_index(op.f('ix_reading_events_book_id'), table_name='reading_events')
    op.drop_table('reading_events')
    op.drop_index(op.f('ix_user_words_word_id'), table_name='user_words')
    op.drop_index(op.f('ix_user_words_child_id'), table_name='user_words')
    op.drop_table('user_words')
    op.drop_index(op.f('ix_reading_sessions_child_id'), table_name='reading_sessions')
    op.drop_index(op.f('ix_reading_sessions_book_id'), table_name='reading_sessions')
    op.drop_table('reading_sessions')
    op.drop_index(op.f('ix_quiz_options_question_id'), table_name='quiz_options')
    op.drop_table('quiz_options')
    op.drop_index(op.f('ix_quiz_attempts_question_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_child_id'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_quiz_questions_book_id'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index(op.f('ix_children_parent_id'), table_name='children')
    op.drop_table('children')
    op.drop_table('book_words')
    op.drop_index(op.f('ix_book_pages_book_id'), table_name='book_pages')
    op.drop_table('book_pages')
    op.drop_table('words')
    op.drop_table('users')
    op.drop_table('books')
    # ### end Alembic commands ###
